name: Build Library

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm i
      - name: Build Library
        run: npm run build:lib
  publish:
    name: Publish to GitHub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create base repo
        if: success()
        working-directory: ./dist/extensions
        run: git init && git checkout -b dist
      - name: Add remote
        working-directory: ./dist/extensions
        run: git remote add origin https://github.com/${{github.repository}}
      - name: Push
        working-directory: ./dist/extensions
        run: git push origin dist
